### ISSUE TITLE
Failed to package app on Linux

### ISSUE THREAD

**Issue by tom-sherman** [railsware/bozon#11]
I run `bozon package` and it fails.

Here's the stack trace: 

```
(node:5361) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:5368) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
/home/tom/thundred/gulpfile.js:5
bozon.task('styles', function () {
      ^

TypeError: bozon.task is not a function
    at Object.<anonymous> (/home/tom/thundred/gulpfile.js:5:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/home/tom/thundred/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/home/tom/thundred/node_modules/liftoff/index.js:193:16)
```

Here's the contents of my `gulpfile.js`:

```javascript
require('bozon/tasks/all')
var sass = require('gulp-sass')

bozon.task('styles', function () {
  return bozon.src('stylesheets/**/*.sass').pipe(sass.sync({
    outputStyle: 'compressed',
    precision: 10
  }).on('error', sass.logError)).pipe(bozon.dest('stylesheets'))
})
```

I feel like I'm missing something simple here...

**Comment by tom-sherman** [comment]
I'm an idiot and shold learn to read the docs :tired_face:
