### ISSUE TITLE
windows build under os x fails

### ISSUE THREAD

**Issue by ellerbrock** [railsware/bozon#19]
hi there,

nice tool, just found it and was happy to use it.
but it looks like it is a outdated. i just wondering if you still support this project or if its better for me to use another build tool?

the error message happens while trying to deploy a windows app under os x:

```[01:01:02] Finished 'html' after 274 ms
[01:01:02] Finished 'styles' after 256 ms
[01:01:02] Finished 'scripts:main' after 255 ms
[01:01:02] Finished 'scripts:renderer' after 255 ms
[01:01:02] Starting 'prepare:app'...
[01:01:02] Finished 'prepare:app' after 35 ms
Warning: "build.osx" is deprecated — please use "mac" instead of "osx"
Skip app dependencies rebuild because platform is different
Warning: app-bundle-id is deprecated, please use appId
Unhandled rejection Error: Cannot check wine version: Error: spawn wine ENOENT```

anyway, even i couldn't use the tool yet thanks for the great work you done for the electron community.

cheers maiky

**Comment by alchapone** [comment]
Hey, of course it is supported. 
Error you're experiencing is actually a known issue. In order to build windows app on OSx, you simply need `wine`, so:

```
brew install wine
```

**Comment by ellerbrock** [comment]
thx for the info, i'm just installing it, found it a  few minutes before you wrote.
would be cool if you write this for others in the readme.md.
also seems like xquartz is needed. `brew install Caskroom/versions/xquartz-beta` after installing i will make a restart and let you know. but anyway, linux threw a error as well when i tried bozen package linux:

```
electron/development/app7
▶ bozen package linux
zsh: command not found: bozen

electron/development/app7                                                                                                                                  ⍉
▶ bozon package linux
(node:73118) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[03:16:57] Using gulpfile /app7/gulpfile.js
[03:16:57] Starting 'html'...
[03:16:57] Starting 'images'...
[03:16:57] Starting 'styles'...
[03:16:57] Starting 'scripts:main'...
[03:16:57] Starting 'scripts:renderer'...
[03:16:58] Finished 'images' after 393 ms
[03:16:58] Version: webpack 1.13.1
         Asset     Size  Chunks             Chunk Names
application.js  1.88 kB       0  [emitted]  main
[03:16:58] Finished 'styles' after 590 ms
[03:16:58] Finished 'scripts:main' after 589 ms
[03:16:58] Finished 'html' after 650 ms
[03:16:58] Finished 'scripts:renderer' after 589 ms
[03:16:58] Starting 'prepare:app'...
[03:16:58] Finished 'prepare:app' after 66 ms
Unhandled rejection Error: Please specify author 'email' in the application package.json ('/app7/builds/production/package.json')

See https://docs.npmjs.com/files/package.json#people-fields-author-contributors

It is required to set Linux .deb package maintainer. Or you can set maintainer in the custom linux options.
(see https://github.com/electron-userland/electron-builder#distributable-format-configuration).

    at Packager.checkMetadata (/app7/node_modules/electron-builder/src/packager.ts:181:15)
    at Packager.<anonymous> (/app7/node_modules/electron-builder/src/packager.ts:68:10)
    at next (native)
    at /app7/node_modules/read-package-json/read-json.js:356:5
    at checkBinReferences_ (/app7/node_modules/read-package-json/read-json.js:320:45)
    at final (/app7/node_modules/read-package-json/read-json.js:354:3)
    at then (/app7/node_modules/read-package-json/read-json.js:124:5)
    at ReadFileContext.<anonymous> (/app7/node_modules/read-package-json/read-json.js:295:20)
    at ReadFileContext.callback (/app7/node_modules/graceful-fs/graceful-fs.js:78:16)
From previous event:
    at tsAwaiter (/app7/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/app7/node_modules/electron-builder/src/builder.ts:190:52)
    at Packager.productionBuild (/.nvm/versions/node/v6.3.0/lib/node_modules/bozon/lib/packaging/packager.js:46:33)
    at Packager.build (/.nvm/versions/node/v6.3.0/lib/node_modules/bozon/lib/packaging/packager.js:19:19)
    at Object.runner.package (/.nvm/versions/node/v6.3.0/lib/node_modules/bozon/lib/bin/runner.js:21:42)
    at Command.<anonymous> (/.nvm/versions/node/v6.3.0/lib/node_modules/bozon/lib/bin/bozon.js:40:19)
    at Command.listener (/.nvm/versions/node/v6.3.0/lib/node_modules/bozon/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/.nvm/versions/node/v6.3.0/lib/node_modules/bozon/node_modules/commander/index.js:615:12)
    at Command.parse (/.nvm/versions/node/v6.3.0/lib/node_modules/bozon/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/.nvm/versions/node/v6.3.0/lib/node_modules/bozon/lib/bin/bozon.js:43:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

```

**Comment by alchapone** [comment]
Ok, looks like I need to update `package.json` which is generated by bozon to include "email" field, to make it work for Linux. Will do that next, thanks!

**Comment by ellerbrock** [comment]
damn sorry, i over read this. so so many times send these info author email bla bla message in npm_debug.log that i did had a closer look. so windows setup finally finish, i make a restart then try it again and write let u know ...

**Comment by ellerbrock** [comment]
![giphy 14](https://cloud.githubusercontent.com/assets/2029255/16903063/d35515b0-4ca5-11e6-8bc5-da15e9246b4c.gif)
awesome app - big helper!
thanks buddy
