### ISSUE TITLE
package cmd. fails w/ Unhandled rejection Error: electron-prebuilt must be in the devDependencies

### ISSUE THREAD

**Issue by semanticdreamer** [railsware/bozon#27]
First things first: AWESOME project ! 👍 

The error...

<details>
  <summary>Unhandled rejection Error: electron-prebuilt must be in the devDependencies - Click to expand</summary>
```
CI detected, so artifacts will be published if draft release exists
Unhandled rejection Error: electron-prebuilt must be in the devDependencies
    at checkDependencies (/dev/code/bozon_test/node_modules/electron-builder/src/packager.ts:310:13)
    at Packager.checkMetadata (/dev/code/bozon_test/node_modules/electron-builder/src/packager.ts:184:5)
    at Packager.<anonymous> (/dev/code/bozon_test/node_modules/electron-builder/src/packager.ts:90:10)
    at next (native)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at tsAwaiter (/dev/code/bozon_test/node_modules/electron-builder/src/util/awaiter.ts:10:47)
    at Object.build (/dev/code/bozon_test/node_modules/electron-builder/out/builder.js:153:12)
    at Packager.productionBuild (/usr/local/lib/node_modules/bozon/lib/packaging/packager.js:46:33)
    at Packager.build (/usr/local/lib/node_modules/bozon/lib/packaging/packager.js:19:19)
    at Object.package (/usr/local/lib/node_modules/bozon/lib/bin/runner.js:21:42)
    at Command.<anonymous> (/usr/local/lib/node_modules/bozon/lib/bin/bozon.js:42:19)
    at Command.listener (/usr/local/lib/node_modules/bozon/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/bozon/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/bozon/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/bozon/lib/bin/bozon.js:45:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
[...]
```
</details>

...occurs for package cmd. for all targets (`osx|windows|linux`).

Simply installing the module `electron-prebuilt` as devDependency does not solve the issue.

I could reproduce for `bozon@0.5.5` on Node `v5.12.0` and `v6.6.0` on OSX 10.12 (Sierra) for a  newly scaffolded otherwise untouched app.

**Comment by kenjinp** [comment]
👍

**Comment by alchaplinsky** [comment]
Ok, use v0.5.6 to bootstrap your new project. For existing one, you'll need to update `dependencies` key to `devDependencies` in your `package.json`

**Comment by semanticdreamer** [comment]
THX @alchaplinsky issue solved, successfully packaged my app :-)

**Comment by alchaplinsky** [comment]
@semanticdreamer  🤘
