### ISSUE TITLE
bozon package linux got : Error: Exit code: ENOENT. spawn gm ENOENT

### ISSUE THREAD

**Issue by QTGate** [railsware/bozon#39]
Hi,
Thank you for your great job.
It looks have error when package linux when do : **bozon package linux**.
I tested '**bozon package linux**' via linux OS , windows OS, mac OS all have same error.
bozon package **mac** and **win** working great.
All test via NodeJS 7.7.3, 
and make a new bozon project with bozon,
then do **bozon start** and got great running.
then do **bozon package linux** no any other touch.
folder: packages/linux-unpacked looks good and have all unpacked files.
> $bozon package linux
[11:24:51] Using gulpfile /qtgate/gulpfile.js
[11:24:51] Starting 'html'...
[11:24:51] Starting 'images'...
[11:24:51] Starting 'styles'...
[11:24:51] Starting 'scripts:main'...
[11:24:51] Starting 'scripts:renderer'...
[11:24:52] Finished 'images' after 143 ms
[11:24:52] Finished 'html' after 194 ms
[11:24:52] Finished 'styles' after 179 ms
[11:24:52] Version: webpack 1.14.0
         Asset     Size  Chunks             Chunk Names
application.js  1.88 kB       0  [emitted]  main
[11:24:52] Finished 'scripts:main' after 211 ms
[11:24:52] Finished 'scripts:renderer' after 211 ms
[11:24:52] Starting 'prepare:app'...
[11:24:52] Finished 'prepare:app' after 29 ms
Skip app dependencies rebuild because platform is different
Packaging for linux x64 using electron 1.6.2 to packages/linux-unpacked
Downloading tmp-1535-0-electron-v1.6.2-linux-x64.zip
[>                                            ] 0.0% (0 B/s)
**Unhandled rejection Error: Exit code: ENOENT. spawn gm ENOENT**
    at /qtgate/node_modules/electron-builder-util/src/util.ts:75:16
    at exithandler (child_process.js:217:5)
    at ChildProcess.errorhandler (child_process.js:229:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at exec (/qtgate/node_modules/electron-builder-util/src/util.ts:53:3)
    at resize (/qtgate/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:155:16)
    at /qtgate/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:158:46
    at Generator.next (<anonymous>)
    at go$readdir$cb (/qtgate/node_modules/graceful-fs/graceful-fs.js:149:14)
    at FSReqWrap.oncomplete (fs.js:114:15)
From previous event:
    at LinuxTargetHelper.createFromIcns (/qtgate/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:216:11)
    at /qtgate/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:54:25
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/qtgate/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:84:11)

**Comment by QTGate** [comment]
This is not issue. Looks I did not have Linux build app on OS.
Here have Multi Platform Build very helply.
[https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build](https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build)

Thanks!
